### ISSUE TITLE
collab-xapi-controls suggested revisions. 

### ISSUE THREAD

**Issue by stgreenb** [CiscoDevNet/labs-xapi#14]
**Step 2:**
Though I get the controls to go to the touch 10 on my room kit. I never see the control in the simulated touch 10. I tried load simulator config and clean up. 
![image](https://user-images.githubusercontent.com/18483964/39493312-6d3e9658-4d60-11e8-97d3-08fb96023b89.png)

**Step 3:** 
Because of all my messing with the simulator, once I am in the editor, I had climate and & lights and blinds as two created pannels. I assume you want to have them remove all pannels first? 
![image](https://user-images.githubusercontent.com/18483964/39493410-c3b1bbdc-4d60-11e8-8f0d-fd1b1b8e537e.png)

![image](https://user-images.githubusercontent.com/18483964/39493437-d71ad4d8-4d60-11e8-86ad-69c1fd0583f9.png)

Note: has both a quote and the beginning of a markdown underscore:  _Note that choosing a color is proposed for CE9.3+" Also don't think proposed is the right word you want here, maybe added is what you want?

"Awesome! but now vey interactive isn'it... No worries: in" -> "Awesome. However its not interactive yet.. No worries. In"

**Step 4:** 
Assume "const MAX = 90 // for a DX80" is also true for a DX70 (which SEVT users will be using)? If so remove 80. 

Maybe write out the "on(‘ready’)" with "xapi.on('ready'" and maybe a statement that indicates that you are replacing everything from that statement till the end of the code. 

I don't think you should reference line numbers as in "On line 12" & "On line 19" because the screen in learning labs doesn't have a number. So they may see numbers in their editor, which would be different, and depending on how they pasted the new code in could be different. 

The last note of the page has a beginning underscore for markdown, but is missing the trailing. 

"Launch the script.." -> "Launch the script (from the command line again)"

At the end of step for do we need to tell the user to ctrl-c to kill the app or should we have that before the next? 

**Step 5**

I screwed up the placement of the new lines of code the first time I tried, so I suspect that others might do the same. Might just need an extra image or note about placement, or just have them paste the whole ending, i.e. everything after the const line, but note that only XX lines were added. 

**Step 7**
Maybe I screwed up placement again, but I am not seeing the note when the volume gets too low (attached and renamed to txt so that github would take it). Though I did when I originally tried from the github version.

[control.txt](https://github.com/CiscoDevNet/labs-xapi/files/1965301/control.txt)

I feel like at the end of step 7 we should have a if your device is cloud registered then "congratulations, you are done (macros will be coming to cloud devices at a later time)" statement.

**Comment by ObjectIsAdvantag** [comment]
Thanks Steve for the feedbacks

**Step 2** 
Looks like we have 2 issues here: the simulator needs refresh for the Touch10 to be updated. Moreover, interactivity with the Touch10/DX will differ whether you launch the simulator from an integrator or remote support account
=> I came up with a new flow to make it straightforward to use the Simulator from a Spark-registered device.

**Step 3**
Definitely, I've added clean up instructions in Step 2 to remove the activities that come with the simulation.

**Step 4**
Got it, removed the lines numbering

**Step 5**
Got it, added guidance to replace and read the code

**Step 7**
The placement in your script is good, it's just that 'api' is mentionned instead of 'xapi' close to on('ready')
