### ISSUE TITLE
Resetting Endpoints

### ISSUE THREAD

**Issue by stgreenb** [CiscoDevNet/labs-xapi#15]
I just noticed that when I went through the lab a 2nd time, that some of the messages I sent to screen were still there. I think we need a reset statement at the beginning (or end for the previous user). 

Though I admit, if the student has enough time, I will have them re-register the device, which I assume would clear it out. But I still think adding a reset statement would be worth it.

**Comment by ObjectIsAdvantag** [comment]
For workshops that are played several times, some kind of reset is certainly desirable.
We typically do Factory Resets on the Sandbox, and a setup script.

I do not see instructions to reset devices being part of the labs themselves.
It's more something that I would as part of the Train The Trainer instructions.

Here are the available options for CE: Reset scripts & Backup / Restore configurations.

For Spark-registered devices, I would certainly go with Reset Scripts, and I would run them from an extra Integrator user (not to mess up with integrator/integrator). 
What about we create a Reset script, and a 'Reset/XXXX' user.

**Comment by dstaudt** [comment]
- I see there is a factory reset xAPI command `xcommand systemunit FactoryReset Confirm: Yes` ...is that what you are recommending Steve?  
- I know also we identified a command to clear the 'Welcome...' setup wizard on the Touch10 after a factory reset: `xcommand FirstTimeWizard: Stop`  ...any other commands we should be running as part of the reset script?
- Will such a factory reset clear configured users ('integrator' and/or 'reset')?
- Will such a factory reset clear registration?
- Will simply re-registering the device cause a factory reset to occur?  (if so, what's the best way to affect a re-registration?)
- If yes to either of the two above, can/should the script include commands to reconfigure users and/or registration (the instructor would need to customize the script accordingly)
- In general, we might want to try and write labs so that even if no clean-up/reset is done, there will be minimal confusion - i.e. no harm if someone left a custom logo image in place, the steps should still work
- If we don't want a full factory reset, we could create a script that simply attempts to undo whatever was modified in the lab (this could leave things in an unknown state if the user changed something weird, however)
- For the SEVT, if it turns out there is plenty of time at the end of each lab (doubtful!), we might want to go ahead and include a final page in each lab asking the user to cleanup/restore any changes they made, or just have the instructor verbally ask them to do it.  I kind of like it as a way to remind the users what was covered, and where things are as they undo each change...

**Comment by ObjectIsAdvantag** [comment]
Here is the script I sketched for the sandbox,
[Sandbox - reset - script.txt](https://github.com/CiscoDevNet/labs-xapi/files/1968413/Sandbox.-.reset.-.script.txt)


we then iterated over it.
You can ask Jacob for the latest version.

**Comment by ObjectIsAdvantag** [comment]
Closing this SEVT related task.
