### ISSUE TITLE
Webex branding alignment

### ISSUE THREAD

**Issue by ObjectIsAdvantag** [CiscoDevNet/labs-xapi#16]
as of the new branding, Webex designates the global brand and also the cloud platform (for meetings, teams and devices)

to reflect this, and aligning with Fabian's communication, I propose we go with:
- Cloud-registered devices
- Room Devices and Desk Devices fall into the larger Webex Devices brand
- a device can be on-prem or cloud-registered. In the latter case, it is registered to the Webex cloud platform (and NOT to Webex teams)
- as Webex teams designates the mobile, desktop, web apps (the clients), a device will pair with a Webex Team app. we can also say a device pairs with Webex Teams.

> Fabian extract: Ever wish you had a big green Join button on your device to get into your meeting? 🔮 It's here! 🙌
> Just as you have a green Join button appear in the Cisco Spark ( 🔜Webex Teams) app… the same Join button will appear on the device! 😍
> How you ask? Simply deploy Hybrid Calendar Service, register the room or desk device to a place, schedule a meeting, and add the cloud-registered device to book the device and meeting. The awake screen will then also show a list of upcoming meetings. ✅
> All the information you need is right here.  👊

**Comment by ObjectIsAdvantag** [comment]
@dstaudt please check the above statement to ensure we're aligned across labs

**Comment by ObjectIsAdvantag** [comment]
It's being also been discussed with DavidB if we should not rename the https://developer.cisco.com/site/roomdevices/ to https://developer.cisco.com/site/webexdevices
in order to align with the new branding

I would suggest we wait a few weeks before moving in that direction, but it is certainly something we want to align by the CLUS timeline

**Comment by dstaudt** [comment]
I'm fine to align on this, especially if the BU approves.  All changes made so far seem fine.  A few points, though:
- 'on-premises' is the more correct formulation: https://www.adamfowlerit.com/2017/04/premise-vs-premises-cares/ though, apropos that article, I think it matters very little.  I may or may not change back instances as I run across them...
- IMHO 'Webex Devices' as the master category for all of these devices whether room/desk or cloud/prem seems...not quite right, especially for on-prem devices where Webex as a service, product or brand may not factor at all
- Again IMHO, 'Cisco Meeting Devices' could work as the master category, with 'Cisco Webex Meeting Devices' designating cloud-registration and 'Cisco Meeting Devices' re-used for on-prem registered.  Confusing still...

I would hate to confuse/dissuade traditional on-prem room device integrators from looking at this content because they see 'Webex' everywhere in the title and descriptions...however maybe it's worth it to emphasize cloud+Webex as the way forward..?

**Comment by ObjectIsAdvantag** [comment]
- +1 to align with "on-premises" moving forward
- for Webex Devices, I've raised it to DavidB and HenrikB, let's see how where it goes. Cisco Collaboration Devices would be my favorite for now.
- concerning device integrators, I am not worried. These will certainly install both on-prem and cloud registered over time.

**Comment by ObjectIsAdvantag** [comment]
Terminology looks aligned with current terminology: Cisco Collaboration Devices, cloud-registered and on-premises registered.
Closing
